version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12
  pre_build:
    commands:
      # Install kustomize
      - echo Install kustomize...
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - ./kustomize version
      - echo "Change directory..."
      # Install yq
      - wget https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      - yq --version
      # Install nodejs application dependencies
      - cd application
      - echo "Installing dependencies..."
      - npm install 
  build:
    commands:
      - echo Build started on `date`
      # Run test
      - echo Run node.js tests...
      - npm run test
      # Get application version 
      - CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
      # Build the Docker images
      - echo Building the Docker image...
      - docker build -t lukondefmwila/express-test:$CONTAINER_IMAGE_TAG .
      # Log in to the Docker CLI
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Push the image to Docker hub
      - echo Pushing the Docker image...
      # - docker push lukondefmwila/dkr-multicontainer-app-client
      # Push local changes to remote repo
      - echo "Create temporary folder to clone the repo into..."
      - TEMP_FOLDER="$(mktemp -d)"
      - echo "Clone the repository..."
      - git clone -b develop https://LukeMwila:$GITHUB_TOKEN@github.com/LukeMwila/fleet-git-ops-pipeline.git ${TEMP_FOLDER}
      - cd ${TEMP_FOLDER}
      # Update K8s manifest with new image tag
      # Redirect to kustomize folder
      - cd ../kustomizations 
      - ./execute-kustomize-dev.sh
      - cd .. 
      - git config user.email "lukemwila.tech@gmail.com"
      - git config user.name "LukeMwila"
      - git add . 
      - git commit -m "refactor - updated dev container image tag to $CONTAINER_IMAGE_TAG"
      - git push -u origin develop